### ISSUE TITLE
PhpMyAdmin

### ISSUE THREAD

**Issue by Elmit2015** [carlosfgti/docker-lemp-php7-phpmyadmin#1]
First of all, thanks for that docker-compose settings.

However, I got a few problems. The README includes some mistakes, so:

> sudo docker exec -it mysql bash

should be:

> sudo docker exec -it mysql_eti bash

then you get access to mysql.

I could not figure out how to connect phpMyAdmin.
http://tool.mydomain.com:8080/index.php shows me the phpMyAdmin login screen, but host mysql_eti / root / root  does not work. Neither does https://tool.mydomain.com:8080/index.php ....

What am I missing?

**Comment by carlosfgti** [comment]
try reconfigure PHPMyAdmin:
**sudo dpkg-reconfigure phpmyadmin**

**Comment by carlosfgti** [comment]
Currently, I use and recommend: http://laradock.io/
