### ISSUE TITLE
phpmyadmin authentication

### ISSUE THREAD

**Issue by faithoflifedev** [carlosfgti/docker-lemp-php7-phpmyadmin#3]
Related to #1 

To get to the phpmyadmin ui use the link [http://localhost:8080/index.php](http://localhost:8080/index.php)

Upon authentication if you see the error:
`SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`

Then do:
`docker exec -it mysql_eti bash`

and

`mysql -u root -p`
`ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';`

I found this solution on [stackoverflow](https://stackoverflow.com/questions/50547724/how-to-resolve-the-error-sql-authentication-method-unknown-in-laravel-mysql)

**Comment by parkkk123** [comment]
pretty useful :) Thank you
